In [1]:
import pandas as pd 
import numpy as np
np.set_printoptions(formatter={'float_kind':'{:f}'.format})

In [2]:
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/OzvzVqK4pgg4x7qEadoZMRyVR/insurance.csv")
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
def categorize(x):
    x = round(x, 1)
    if x<18.5:
        return 'Underweight'
    if x>=18.5 and x <=24.9:
        return 'Normal'
    if x>=25 and x<=29.9:
        return 'Overweight'
    if x>=30:
        return 'Obese'
df['BMI_group'] = df['bmi'].apply(categorize)
df.head(5)

age     sex     bmi  children smoker     region      charges   BMI_group
0   19  female  27.900         0    yes  southwest  16884.92400  Overweight
1   18    male  33.770         1     no  southeast   1725.55230       Obese
2   28    male  33.000         3     no  southeast   4449.46200       Obese
3   33    male  22.705         0     no  northwest  21984.47061      Normal
4   32    male  28.880         0     no  northwest   3866.85520  Overweight

In [4]:
# cut_bins = [0,18.4,24.9, 29.9, 30.001]
# cut_labels = [ 'Underweight', 'Normal', 'Overweight', 'Obese']
# df['BMI_group'] = pd.cut(df['bmi'].clip(upper=30), bins=cut_bins,include_lowest =True, labels=cut_labels)
# df.head(5)

In [5]:
df.loc[df.bmi==18.5]

age     sex   bmi  children smoker     region   charges BMI_group
684   33  female  18.5         1     no  southwest  4766.022    Normal

In [6]:
df.loc[(df.bmi>24.9) & (df.bmi<25)]

age     sex     bmi  children smoker     region      charges   BMI_group
367    42  female  24.985         2     no  northwest   8017.06115  Overweight
1008   25    male  24.985         2     no  northeast  23241.47453  Overweight
1221   40    male  24.970         2     no  southeast   6593.50830  Overweight

In [7]:
df.loc[df.bmi==29.9]

age     sex   bmi  children smoker     region    charges   BMI_group
865    40    male  29.9         2     no  southwest   6600.361  Overweight
1126   55    male  29.9         0     no  southwest  10214.636  Overweight
1263   43  female  29.9         1     no  southwest   7337.748  Overweight

In [8]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
pd.set_option('display.max_columns', 500)
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/831JKKEkW7kqd5M4evNva9LyB/insurance_grouped.csv")
le = LabelEncoder()#use this encoder to encode values
def categorize(x):
    x = round(x, 1)
    if x<18.5:
        return 'Underweight'
    if x>=18.5 and x <=24.9:
        return 'Normal'
    if x>=25 and x<=29.9:
        return 'Overweight'
    if x>=30:
        return 'Obese'

df['BMI_group'] = df['bmi'].apply(categorize)



In [9]:
df.head()

age     sex     bmi  children smoker     region      charges   BMI_group
0   19  female  27.900         0    yes  southwest  16884.92400  Overweight
1   18    male  33.770         1     no  southeast   1725.55230       Obese
2   28    male  33.000         3     no  southeast   4449.46200       Obese
3   33    male  22.705         0     no  northwest  21984.47061      Normal
4   32    male  28.880         0     no  northwest   3866.85520  Overweight

In [10]:
df['age'].describe()

count    1338.000000
mean       39.207025
std        14.049960
min        18.000000
25%        27.000000
50%        39.000000
75%        51.000000
max        64.000000
Name: age, dtype: float64

In [11]:
df['age'] = le.fit_transform(df['age'])
df['sex'] = le.fit_transform(df['sex'])
df['BMI_group'] = df['BMI_group'].fillna('None')
df['BMI_group'] = le.fit_transform(df['BMI_group'])
df['smoker'] = le.fit_transform(df['smoker'])
df['region'] = le.fit_transform(df['region'])

print(df.head(5))

   age  sex     bmi  children  smoker  region      charges  BMI_group
0    1    0  27.900         0       1       3  16884.92400          2
1    0    1  33.770         1       0       2   1725.55230          1
2   10    1  33.000         3       0       2   4449.46200          1
3   15    1  22.705         0       0       1  21984.47061          0
4   14    1  28.880         0       0       1   3866.85520          2


In [12]:
df[['smoker',"bmi", "age","charges"]]

smoker     bmi  age      charges
0          1  27.900    1  16884.92400
1          0  33.770    0   1725.55230
2          0  33.000   10   4449.46200
3          0  22.705   15  21984.47061
4          0  28.880   14   3866.85520
...      ...     ...  ...          ...
1333       0  30.970   32  10600.54830
1334       0  31.920    0   2205.98080
1335       0  36.850    0   1629.83350
1336       0  25.800    3   2007.94500
1337       1  29.070   43  29141.36030

[1338 rows x 4 columns]

In [13]:
c = df[['smoker',"bmi", "age","charges"]].corr()
c

smoker       bmi       age   charges
smoker   1.000000  0.003750 -0.025019  0.787251
bmi      0.003750  1.000000  0.109272  0.198341
age     -0.025019  0.109272  1.000000  0.299008
charges  0.787251  0.198341  0.299008  1.000000

In [14]:
c.loc['smoker', 'age']

-0.025018751536284797

In [15]:
import pandas as pd 
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/B5yO4wkEbQk4dVGn8140yV1bx/insurance_encoded.csv")


c = df[['smoker',"bmi", "age","charges"]].corr()
print(round(c.loc['smoker', 'bmi'], 3))
print(round(c.loc['smoker', 'age'], 3))
print(round(c.loc['smoker', 'charges'], 3))

0.004
-0.025
0.787


In [16]:
import pandas as pd

# Read training data
train = pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/72Boxj99702g8BwK5powGz1g0/insurance_training.csv")

# Read test data
test = pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/gxVjwe1k3YEogYK23O8PPnXod/insurance_test.csv")

In [17]:
train.head()

Unnamed: 0  age  sex    bmi  children  smoker  region  BMI_group  \
0         560   46    0  19.95         2       0       1          1   
1        1285   47    0  24.32         0       0       0          1   
2        1142   52    0  24.86         0       0       2          1   
3         969   39    0  34.32         5       0       2          2   
4         486   54    0  21.47         3       0       1          1   

       charges  
0   9193.83850  
1   8534.67180  
2  27117.99378  
3   8596.82780  
4  12475.35130

In [18]:
test.head()

Unnamed: 0  age  sex     bmi  children  smoker  region  BMI_group
0         764   45    0  25.175         2       0       0          3
1         887   36    0  30.020         0       0       1          2
2         890   64    0  26.885         0       1       1          3
3        1293   46    1  25.745         3       0       1          3
4         259   19    1  31.920         0       1       1          2

In [19]:
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [20]:
train.drop('Unnamed: 0', axis=1)
test.drop('Unnamed: 0', axis=1)

age  sex     bmi  children  smoker  region  BMI_group
0     45    0  25.175         2       0       0          3
1     36    0  30.020         0       0       1          2
2     64    0  26.885         0       1       1          3
3     46    1  25.745         3       0       1          3
4     19    1  31.920         0       1       1          2
..   ...  ...     ...       ...     ...     ...        ...
263   63    1  35.090         0       1       2          2
264   58    0  27.170         0       0       1          3
265   38    1  28.025         1       0       0          3
266   54    0  47.410         0       1       2          2
267   51    0  34.200         1       0       3          2

[268 rows x 7 columns]

In [21]:
len(test.index)

268

In [22]:
x_train=train['smoker']
y_train=train['charges']

In [23]:
# Add a constant to get an intercept
X_train_sm = sm.add_constant(x_train)

# Fit the resgression line using 'OLS'
lr = sm.OLS(y_train, X_train_sm).fit()

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


In [24]:
print(lr.summary())

                            OLS Regression Results                            
Dep. Variable:                charges   R-squared:                       0.608
Model:                            OLS   Adj. R-squared:                  0.608
Method:                 Least Squares   F-statistic:                     1660.
Date:                Sat, 11 Apr 2020   Prob (F-statistic):          1.04e-219
Time:                        23:30:33   Log-Likelihood:                -11068.
No. Observations:                1070   AIC:                         2.214e+04
Df Residuals:                    1068   BIC:                         2.215e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       8578.3225    258.076     33.240      0.0

In [25]:
X_test=test['smoker']

In [26]:
# Add a constant to X_test
X_test_sm = sm.add_constant(X_test)

# Predict the y values corresponding to X_test_sm
y_test_pred = lr.predict(X_test_sm)

In [28]:
from sklearn.metrics import r2_score
r_squared = r2_score(y_test, y_pred)
r_squared

NameError: name 'y_test' is not defined

In [1]:
# Importing the Pandas package and reading the data
import pandas as pd
wholesale = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/OkbnaOBqrBXZOpRQw1JGMgaM9/Wholesale_Data.csv')

# Write your code here. Make sure that you change the values in the column 'Channel' inplace. 






# The final print statement. Please don't edit this part. Also don't write any other
# print statement otherwise your answer will not match even if it is correct
print(wholesale['Channel'].value_counts())

H             47
Cafe          45
Caffe         42
R             42
C             36
Hote          35
Hot           32
Hotel         32
Restaurant    30
Rest          29
Name: Channel, dtype: int64


In [4]:
def mapList(x):
    if x[0]=='H':
        return 'Hotel'
    elif x[0]=='C':
        return 'Cafe'
    else:
        return 'Restaurant'
wholesale['Channel'] = wholesale['Channel'].apply(mapList)
print(wholesale['Channel'].value_counts())

Hotel         146
Cafe          123
Restaurant    101
Name: Channel, dtype: int64


In [5]:
wholesale.head()

Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen Channel
0  12669  9656     7561     214              2674        1338    Cafe
1   7057  9810     9568    1762              3293        1776   Hotel
2   6353  8808     7684    2405              3516        7844   Hotel
3  13265  1196     4221    6404               507        1788    Cafe
4  22615  5410     7198    3915              1777        5185   Hotel

In [6]:
wholesale['total'] = wholesale['Fresh']+wholesale['Milk']+wholesale['Grocery']+wholesale['Frozen']+wholesale['Detergents_Paper']+wholesale['Delicassen']
m = wholesale.groupby('Channel')['total'].sum()
print(m.idxmin())
wholesale.head()

Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen Channel  total
0  12669  9656     7561     214              2674        1338    Cafe  34112
1   7057  9810     9568    1762              3293        1776   Hotel  33266
2   6353  8808     7684    2405              3516        7844   Hotel  36610
3  13265  1196     4221    6404               507        1788    Cafe  27381
4  22615  5410     7198    3915              1777        5185   Hotel  46100

Restaurant


In [12]:
m.idxmin()

'Restaurant'

In [14]:
import math
math.sqrt(7)

2.6457513110645907

In [21]:
n=input()
l = len(n)
n = int(n)
res = 0
while n>0:
#     print(n%10)
#     print((n%10)**l)
    res = res+((n%10)**l)
    print(res)
    n=n//10
    
print(res ==n)

153
27
152
153
False


In [20]:
27+125+1

153

In [22]:
import pandas as pd
import ast,sys
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/X0kvr3wEYXRzONE5W37xWWYYA/test.csv")

In [24]:
df.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [57]:
to_omit = ['SibSp', 'Pclass', 'Name', 'Sex','Embarked']


In [58]:
display = df.columns[~df.columns.isin(to_omit)].values
print(type(display))
display.sort()
print(df[display].head())

<class 'numpy.ndarray'>
    Age Cabin     Fare  Parch  PassengerId   Ticket
0  34.5   NaN   7.8292      0          892   330911
1  47.0   NaN   7.0000      0          893   363272
2  62.0   NaN   9.6875      0          894   240276
3  27.0   NaN   8.6625      0          895   315154
4  22.0   NaN  12.2875      1          896  3101298


In [61]:
series1 = pd.Series([1,2,3,4,5,6,7])
series2 = pd.Series([1,3,7])


In [63]:
myindex

1    0
2    1
3    2
4    3
5    4
6    5
7    6
dtype: int64

In [70]:
myindex = pd.Series(series1.index, index=series1)
res = myindex[series2].values
res.sort()
print(res)

[0 2 6]


In [71]:
import pandas as pd 
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/8NMooe4G0ENEe8z9q5ZvaZA7/googleplaystore.csv")
#add your cleaning code here


        Rating
Rating     1.0


In [72]:
df.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [7]:
# Read the input string
def converToProp(input_string):
    res =''
    flag=0
    index=0
    input_string = input_string.lower()
    for i in input_string:
        if i =='_':
            flag=1
        elif flag==1 or index==0:
            res=res+i.upper()
            flag=0
            index+=1
        else:
            res=res+i

    print( res+'=,')

In [11]:
# l = ['plan_id','session_id','session_start_date','first_payment_due','is_family_based','is_student_based','reporting_type','cc_fee_payable','is_early_registartion_fee','es_standard_fee','is_advance_payment','ap_apply_flag','ap_distribution_flag','active_status','session_end_date','fsa_report_start_date']
l=['PAYMENT_METHOD_AUTO','PAYMENT_METHOD_MAILIN','PAYMENT_METHOD_ADVANCED_PAYMENTS','PAYMENT_METHOD_ADVANCED','PAYMENT_METHOD_INSCHOOL','PAYMENT_METHOD_COUPON','PAYMENT_METHOD_AUTO_DEBIT_CC','PAYMENT_METHOD_PHONE','PAYMENT_METHOD_AUTO_ECHECK','PAYMENT_METHOD_AUTO_CC','PAYMENT_METHOD_BANK_TRANSFER_CHECKING','PAYMENT_METHOD_BANK_TRANSFER_SAVING','PAYMENT_METHOD_WEB','PAYMENT_METHOD_LATEFEE_CREDIT','PAYMENT_METHOD_BANKFEE_CREDIT','BUY NOW','GIVE NOW','PAYMENT_METHOD_SMARTSHIELD','TX_PAYMENT_METHOD_CC','TX_PAYMENT_METHOD_ECHECK']


for i in l:
    converToProp(i)

PaymentMethodAuto,
PaymentMethodMailin,
PaymentMethodAdvancedPayments,
PaymentMethodAdvanced,
PaymentMethodInschool,
PaymentMethodCoupon,
PaymentMethodAutoDebitCc,
PaymentMethodPhone,
PaymentMethodAutoEcheck,
PaymentMethodAutoCc,
PaymentMethodBankTransferChecking,
PaymentMethodBankTransferSaving,
PaymentMethodWeb,
PaymentMethodLatefeeCredit,
PaymentMethodBankfeeCredit,
Buy now,
Give now,
PaymentMethodSmartshield,
TxPaymentMethodCc,
TxPaymentMethodEcheck,


In [ ]:
# Read the input string
def converToProp(input_string):
    res =''
    flag=0
    index=0
    
    for i in input_string:
        if i =='_':
            flag=1
        elif flag==1 or index==0:
            res=res+i.upper()
            flag=0
            index+=1
        else:
            res=res+i

    print(input_string, res)

In [1]:
import numpy as np

In [10]:
b1 = np.array( [[2, -2], [1, 1]] )
b2 = np.array( [[3, -3], [2, 2]] )
b2I = np.linalg.inv(b2)
b1I = np.linalg.inv(b1)
m = b2I @ b1
m1 = b1I @ b2

In [11]:
v = np.array([[11], [13]])

In [12]:
m1 @ v

array([[22.5],
       [25.5]])

In [13]:
b1 = np.array( [[1, 0], [0, 1]] )
b2 = np.array( [[1, 1], [-2,1]] )
b2I = np.linalg.inv(b2)
b1I = np.linalg.inv(b1)
m = b2I @ b1
m1 = b1I @ b2

In [14]:
m

array([[ 0.33333333, -0.33333333],
       [ 0.66666667,  0.33333333]])

In [15]:
b2I

array([[ 0.33333333, -0.33333333],
       [ 0.66666667,  0.33333333]])

In [17]:
c = np.array([[21], [12]])
m @ c

array([[ 3.],
       [18.]])

In [18]:
c = np.array([[25], [28]])
m @ c

array([[-1.],
       [26.]])

In [19]:
c = np.array([[-3], [12]])
m1 @ c

array([[ 9.],
       [18.]])

In [24]:
v1 = np.array( [[1,3,1,3], [3,2,2,2], [4, 4, 3, 1], [2, 1, 4, 1]] )
v2 = np.array( [[1, 3, 1, 1], [1, 3, 2,2], [2, 2, 2, 2], [3, 1, 3, 1]] )
b2I = np.linalg.inv(v2)
m = b2I @ v1
m

array([[0.500000, 2.500000, 0.750000, 0.250000],
       [-0.500000, 0.500000, -0.250000, 1.250000],
       [-0.500000, -3.000000, 0.500000, -0.000000],
       [2.500000, 2.000000, 0.500000, -1.000000]])

In [25]:
v = np.array([[2], [4], [5], [2]])
m@v

array([[15.250000],
       [2.250000],
       [-10.500000],
       [13.500000]])

In [27]:
matrix = np.array([[3,1], [8,-16]])

inv = np.linalg.inv(matrix)

In [28]:
inv

array([[0.285714, 0.017857],
       [0.142857, -0.053571]])

In [29]:
v = np.array([[3], [2]])
inv @ v

array([[0.892857],
       [0.321429]])

In [7]:
a = [[2, 1], [3,2 ], [2 , 1], [5, 1]]

In [8]:
b=['X', 'Y']

In [9]:
data = pd.DataFrame(a, columns=b)
data

X  Y
0  2  1
1  3  2
2  2  1
3  5  1

In [10]:
np.cov(data.T)

array([[2.  , 0.  ],
       [0.  , 0.25]])

In [ ]:
v2 = np.array( [[1, 3, 1, 1], [1, 3, 2,2], [2, 2, 2, 2], [3, 1, 3, 1]] )
b2I = np.linalg.inv(v2)

In [2]:
a = np.array([[9.16,19.61], [19.61, 42.23]])
b = np.array([[0.422,0.907], [0.907, -0.422]])
b @ a

array([[21.651790, 46.578030],
       [0.032700, -0.034790]])

In [8]:
a = np.array([[2,2], [5, 1]])
print(a.shape)
a

(2, 2)


array([[2, 2],
       [5, 1]])

In [9]:
s =np.sum(a, axis=1, keepdims=True)
print(s.shape)
s

(2, 1)


array([[4],
       [6]])

In [10]:
s =np.sum(a, axis=1)
print(s.shape)
s

(2,)


array([4, 6])

In [1]:
a = list(range(1, 7))
b = list(range(10, 20))

In [2]:
def Generator(flag=True):
    a_idx = 0
    a_len = len(a)
    b_idx = 0
    b_len = len(b)
    while True:
        if(flag):
            yield a[a_idx]
            a_idx = (a_idx+1)%a_len
        else:
            yield b[b_idx]
            b_idx = (b_idx+1)%b_len

In [3]:
a_gen = Generator()
for i in range(10):
    print(next(a_gen))

1
2
3
4
5
6
1
2
3
4


In [4]:
b_gen = Generator(False)
for i in range(15):
    print(next(b_gen))

10
11
12
13
14
15
16
17
18
19
10
11
12
13
14


In [5]:
a_gen2 = Generator()
for i in range(10):
    print(next(a_gen2))

1
2
3
4
5
6
1
2
3
4
