In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np


In [3]:
ds  = pd.read_csv('Salary_Data.csv')

In [4]:
ds.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [5]:
ds.tail()

YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [6]:
from sklearn.model_selection import train_test_split

In [11]:
x = ds.iloc[:, :-1].values
y = ds.iloc[:, 1].values

In [2]:
input_list = [0, 2, 0, 0, 1, 1, 2, 0, 1]

n= len(input_list)
i=0
j=n-1
for k in range(n):
    print(input_list[i], input_list[j] ,input_list[k])
    if input_list[k]==0:
        temp = input_list[i]
        input_list[i] = input_list[k]
        input_list[k] = temp
        i = i+1
    elif input_list[k]==2:
        print
        temp = input_list[j]
        input_list[j] = input_list[k]
        input_list[k] = temp
        j=j-1
    print(input_list)
    

0 1 0
[0, 2, 0, 0, 1, 1, 2, 0, 1]
2 1 2
[0, 1, 0, 0, 1, 1, 2, 0, 2]
1 0 0
[0, 0, 1, 0, 1, 1, 2, 0, 2]
1 0 0
[0, 0, 0, 1, 1, 1, 2, 0, 2]
1 0 1
[0, 0, 0, 1, 1, 1, 2, 0, 2]
1 0 1
[0, 0, 0, 1, 1, 1, 2, 0, 2]
1 0 2
[0, 0, 0, 1, 1, 1, 0, 2, 2]
1 0 2
[0, 0, 0, 1, 1, 1, 2, 0, 2]
1 1 2
[0, 0, 0, 1, 1, 2, 2, 0, 1]


In [1]:
def Unknown_func(number):
    if number == 0:
        return 0
    else:
        return number*number + Unknown_func(number-1)

Unknown_func(4)

30

In [6]:
input_str = input()
input_list = input_str.split(',')

a = int(input_list[0])
b = int(input_list[1])
c = int(input_list[2])

# write code here
def large_sum(a, b, c):
    res = 0
    for i in range(b+1):
        res = res+F(i)
    return res

d ={}
def F(n):
    if n in d:
        temp= d[n]
    elif n>b:
        temp= n-c
        d[n] = temp
    else:
        for i in range(4):
            temp=n
            temp = F(a+temp)
#         temp = F(a + F(a + F(a + F(a + n))))
        d[n] = temp
    return temp

# store the result in the following variable
result = large_sum(a, b, c)

# print result -- do not change the following code
print(result)

2,3,4
2


In [5]:
arr=[1, 2, 3, 4, 5,6 , 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
a = np.array(arr)
a = a.reshape(4, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [6]:
a[ : , :2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [7]:
a[ : , :3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [8]:
A = np.eye(3)
n = 2
A[0], A[n] = A[n], A[0]
print(A)

[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
A = np.eye(3)
n = 2
A[[0,n]] = A[[n,0]]
print(A)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [15]:
a = np.array([[4 ,3, 1],
     [5 ,7, 0],
     [9, 9, 3],
     [8 ,2, 4]])

In [16]:
a[[1, 3]] = a[[3, 1]]
a

array([[4, 3, 1],
       [8, 2, 4],
       [9, 9, 3],
       [5, 7, 0]])

In [36]:
res = np.array([])
n=3
a = np.ones(n)
res = np.append(res, a, axis=1)
b = np.zeros(n)
b[0]  = 1
b[n-1] = 1
for i in range(n-2):
    res = np.append(res,b, axis=1)
res = np.append(res,a, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [35]:
print(res)

[1. 1. 1. 1. 0. 1. 1. 1. 1.]


In [39]:
a = np.ones((n, n), dtype=int)

In [40]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [2]:
input_str = input()
input_list = input_str.split(',')

a = int(input_list[0])
b = int(input_list[1])
c = int(input_list[2])

# write code here
def large_sum(a, b, c):
    res = 0
    for i in range(b+1):
        res = res+F(i)
    return res

d ={}
def F(n):
    if n in d:
        temp= d[n]
    elif n>b:
        temp= n-c
        d[n] = temp
    else:
        temp=n
        for i in range(4):
            
            temp = F(a+temp)
#         temp = F(a + F(a + F(a + F(a + n))))
        d[n] = temp
    return temp

# store the result in the following variable
result = large_sum(a, b, c)

# print result -- do not change the following code
print(result)

20, 100, 15


RecursionError: maximum recursion depth exceeded in comparison

In [ ]:
mylist1 = [True,  True,  True, False,  True]
mylist2 = [False, True, False,  True, False]

mylist1

In [3]:
import ast, sys

In [27]:
input_str = "[{'garden1':'Roses'}, {'garden2':'Lilies'}, {'garden3':'roses'}, {'garden4':'Mangoes'}]"
input_dict = ast.literal_eval(input_str)
input_dict

[{'garden1': 'Roses'},
 {'garden2': 'Lilies'},
 {'garden3': 'roses'},
 {'garden4': 'Mangoes'}]

In [28]:
a = set()

In [29]:
for i in input_dict:
    for v in i.values():
        a.add(v)
print(a)
print(len(a))

{'roses', 'Roses', 'Lilies', 'Mangoes'}
4


In [9]:
a

{1}

In [14]:
tuple(input_dict[0].values())


('Roses',)

In [30]:
def gcd(a, b):

ZeroDivisionError: integer division or modulo by zero

In [40]:
n = input()
l = len(n)
num = int(n)
s = 0
while(num>0):
#     d = n%10
    s = s+pow(num%10, l)
    print
    num = num//10
    
    
print(s)

370
370


In [46]:
n =5
l=[]

a=0
b=1
if n>0:
    l.append(a)
if n>1:
    l.append(b)
c=a+b
while c<n:
    l.append(c)
    a = b
    b = c
    c = a+b
    
print(l)
    
    

[0, 1, 1, 2, 3]


In [75]:
import numpy as np
array1 = np.array([1, 2])
array2 = np.array([1,2,2, 3])

In [76]:
d1  = dict(zip(*np.unique(array1, return_counts=True)))

In [77]:
d2 = dict(zip(*np.unique(array2, return_counts=True)))

In [78]:
res = "Equal"

In [74]:
if len(d2.keys()) == len(d1.keys()):
    
else:
    res = "Not equal"

3

In [79]:
l = ["mumbai", "pune", "goa"]
s = "goa"
s in l

True

In [80]:
l = [1, 3, 5]
s = "1"
s in l

False

In [2]:
a = np.array([[2, 7, 1], [-2, 1, 8], [3,4,-2]])
b = np.array([[8,1,3], [3,5, 8], [7,-2, -4]])
a @ b

array([[ 44,  35,  58],
       [ 43, -13, -30],
       [ 22,  27,  49]])

In [5]:
a = np.array([[2 , 1, 1], [3, 2, 1], [2 , 1, 2]])
np.linalg.inv(a)

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])