In [6]:
import numpy as np

In [7]:
array_id = np.array([2, 4, 5, 6, 7, 8])
print(array_id)
print(type(array_id))

[2 4 5 6 7 8]
<class 'numpy.ndarray'>


In [8]:
array_id = np.array([[2, 4, 5], [6, 7, 8]])
print(array_id)
print(type(array_id))

[[2 4 5]
 [6 7 8]]
<class 'numpy.ndarray'>


In [9]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
l3 =[7, 8, 9]
l = [l1, l2, l3]

In [10]:
print(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [11]:
a = np.array(l).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(a.shape)

(3, 3)


In [13]:
l = [1, 2, 3, 4, 5, 6 , 7, 8, 9]

In [25]:
a = np.array([[[0, 1, 2, 0, 1, 2]],
       [[0, 1, 2, 0, 1, 2]]])
print(a)
print(a.shape)

[[[0 1 2 0 1 2]]

 [[0 1 2 0 1 2]]]
(2, 1, 6)


In [2]:
n= 4
print(n/2)
print(n%2)

2.0
0


In [15]:
m = np.array(l).reshape(3, 3)
print(m.shape)
(r, c) = m.shape
print(r, c)

(3, 3)
3 3


In [18]:
a = np.zeros((1, 0))

In [22]:
a.size

0

In [23]:
len(a)

1

In [24]:

import numpy as np 
import pandas as pd 
s = pd.Series(np.arange(1, n+1, dtype = int)**2, index = np.arange(1, n+1, dtype = int))

In [25]:
s

1     1
2     4
3     9
4    16
dtype: int32

In [26]:
gold = pd.DataFrame({'Country': ['USA', 'France', 'Russia'],
                         'Medals': [15, 13, 9]}
                    )
silver = pd.DataFrame({'Country': ['USA', 'Germany', 'Russia'],
                        'Medals': [29, 20, 16]}
                    )
bronze = pd.DataFrame({'Country': ['France', 'USA', 'UK'],
                        'Medals': [40, 28, 27]}
                    )

In [37]:
gold

Medals
Country        
USA          15
France       13
Russia        9

In [38]:
silver

Medals
Country        
USA          29
Germany      20
Russia       16

In [39]:
bronze

Medals
Country        
France       40
USA          28
UK           27

In [36]:
gold.set_index('Country', inplace = True)
silver.set_index('Country', inplace = True)
bronze.set_index('Country', inplace = True)


In [40]:
gold+silver

Medals
Country        
France      NaN
Germany     NaN
Russia     25.0
USA        44.0

In [41]:
gold.add(silver, fill_value = 0).add(bronze, fill_value = 0)

Medals
Country        
France     53.0
Germany    20.0
Russia     25.0
UK         27.0
USA        72.0

In [50]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
#Type your groupby command here
df.head()
df_1 = df.groupby(['month', 'day'])
df_1['rain', 'wind'].mean()

rain      wind
month day                    
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
      tue  0.000000  8.500000
      wed  0.000000  8.000000
feb   fri  0.000000  4.820000
      mon  0.000000  4.500000
      sat  0.000000  2.350000
      sun  0.000000  2.550000
      thu  0.000000  3.100000
      tue  0.000000  5.850000
      wed  0.000000  3.100000
jan   sat  0.000000  3.100000
      sun  0.000000  0.900000
jul   fri  0.000000  4.300000
      mon  0.000000  3.800000
...             ...       ...
      wed  0.066667  6.266667
jun   fri  0.000000  4.800000
      mon  0.000000  4.766667
      sat  0.000000  2.900000
      sun  0.000000  2.450000
      thu  0.000000  6.050000
      wed  0.000000  4.633333
mar   fri  0.018182  5.863636
      mon  0.000000  4.083333
      sat  0.000000  5.010000
      sun  0.000000  4.600000
      thu  0.000000  4.480000
      tue  0.000000  5.380000
      wed  0.000000  5.800000
may   fri  0.000000  4.000000
      sat  0.000000  4.900000
nov   tue  0.000000  4.500000
oct   fri  0.000000  5.400000
      mon  0.000000  4.350000
      sat  0.000000  2.800000
      sun  0.000000  3.000000
      tue  0.000000  2.700000
      wed  0.000000  3.150000
sep   fri  0.000000  3.910526
      mon  0.000000  3.107143
      sat  0.000000  3.460000
      sun  0.000000  3.955556
      thu  0.000000  3.357143
      tue  0.000000  3.431579
      wed  0.000000  3.378571

[64 rows x 2 columns]

KeyError: 'Column not found: Profit'