In [1]:
import numpy as np
import pandas as pd
import PyPDF2 

In [2]:
# creating a pdf file object 
pdfFileObj = open('Desktop/example.pdf', 'rb') 

In [3]:
# creating a pdf reader object 
pdfReader = PyPDF2.PdfFileReader(pdfFileObj) 

In [4]:
# printing number of pages in pdf file 
print(pdfReader.numPages)

1


In [5]:
# creating a page object 
pageObj = pdfReader.getPage(0) 

# extracting text from page 
print(pageObj.extractText()) 
  
# closing the pdf file object 
pdfFileObj.close() 

In [8]:
df = pd.read_csv('Desktop/melbourne.csv')

In [9]:
df.head()

Suburb             Address  Rooms Type      Price Method SellerG  \
0  Abbotsford       68 Studley St      2    h        NaN     SS  Jellis   
1  Abbotsford        85 Turner St      2    h  1480000.0      S  Biggin   
2  Abbotsford     25 Bloomburg St      2    h  1035000.0      S  Biggin   
3  Abbotsford  18/659 Victoria St      3    u        NaN     VB  Rounds   
4  Abbotsford        5 Charles St      3    h  1465000.0     SP  Biggin   

         Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  03-09-2016       2.5    3067.0  ...       1.0  1.0     126.0           NaN   
1  03-12-2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
2  04-02-2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
3  04-02-2016       2.5    3067.0  ...       2.0  1.0       0.0           NaN   
4  04-03-2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN        Yarra  -37.8014    144.9958  Northern Metropolitan   
1        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan   
2     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan   
3        NaN        Yarra  -37.8114    145.0116  Northern Metropolitan   
4     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [7]:
a = np.array([-1, 3])
print(a)
print(a.shape)
b = a[np.newaxis, :]
print(b)
print(b.shape)
c = a[:, np.newaxis]
print(c)
print(c.shape)

[-1  3]
(2,)
[[-1  3]]
(1, 2)
[[-1]
 [ 3]]
(2, 1)


In [28]:
x1 = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(2, 2, 2)
x2 = np.array([5, 4, 3])
x2.shape

(3,)

In [29]:
x2n = x2[:, np.newaxis]
x2n.shape

(3, 1)

In [30]:
x1+x2n

ValueError: operands could not be broadcast together with shapes (2,2,2) (3,1) 

In [31]:
x1 = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(2, 2, 2)
print(x1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
x1.shape

(2, 2, 2)

In [35]:
x2 = x1[:, np.newaxis, :]
x2.shape

(2, 1, 2, 2)

In [36]:
print(x2)

[[[[1 2]
   [3 4]]]


 [[[5 6]
   [7 8]]]]


In [8]:
#take input on your own
data =[15, 16, 17, 18, 11, 12, 13, 14]

key = 12

#find key in rotated list
res = -1
l = 0 
r = len(data)-1

while(l<=r):
    mid = (r+l)//2    
    if data[mid]==key:
        res = mid
        break
    elif data[l]<=data[mid]:
        if key>=data[l] and key<data[mid]:
            r = mid-1
        else:
            l = mid+1
    elif data[l]>data[mid]:
        if key>data[mid] and key<=data[r]:
            l = mid + 1
        else:
            r = mid - 1

print(res)

5


In [16]:
#take input here
import math
import ast
data = [3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27]
key = 17
res = -1
l= 0 
r = len(data)-1

while(l<=r):
    mid1 = l + (r-l)//3
    mid2 = r - (r-l)//3
    if data[mid1] == key:
        res = mid1
    elif data[mid2] == key:
        res = mid2
    
    if key<data[mid1]:
        r = mid1-1
    elif key>data[mid2]:
        l = mid2+1
    else:
        l = mid1+1
        r = mid2-1

print(res)

7


In [9]:
def ternarySearch(key, ar):
    l = 0
    r = len(ar)-1
    while r >= l: 
          
        # Find mid1 and mid2 
        mid1 = l + (r-l) // 3
        mid2 = r - (r-l) // 3
  
        # Check if key is at any mid 
        if key == ar[mid1]: 
            return mid1 
        if key == mid2: 
            return mid2 
  
        # Since key is not present at mid,  
        # Check in which region it is present 
        # Then repeat the search operation in that region 
        if key < ar[mid1]: 
            # key lies between l and mid1 
            r = mid1 - 1
        elif key > ar[mid2]: 
            # key lies between mid2 and r 
            l = mid2 + 1
        else: 
            # key lies between mid1 and mid2 
            l = mid1 + 1
            r = mid2 - 1
  
    # key not found 
    return -1

In [11]:
data = [3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27]
key = 17
print(len(data))
ternarySearch(key, data)

13


-1

In [33]:
valley_list = [13, 11, 8, 7, 6, 4, 3, 2, 1, 14, 15, 16, 17]
key = 32
res = -1
l = 0 
r= len(valley_list)-1
while(l<=r):
    mid = (l+r)//2
    if key == valley_list[mid]:
        res = mid
        break
    
    if valley_list[l]>valley_list[mid]: #left part is sorted in descending order
        if key>=valley_list[l] and key <valley_list[mid]:
            res  = binary_search_desc(l, mid-1 , valley_list, key)
            break
        else:
            l = mid+1
    

SyntaxError: invalid syntax (<ipython-input-33-60a323f3a551>, line 18)

In [30]:
def binary_search_desc(l , r, sorted_list, key):
    res = -1
    while(l<=r):
        mid = l+ (r-l)//2
        if( sorted_list[mid] ==key):
            res = mid
            break
        elif (sorted_list[mid]>key):
            l = mid+1
        else:
            r = mid-1
    return res

print(binary_search_desc(0 , 5,  valley_list, 32))

-1


In [29]:
valley_list = [13, 1, 2, 3, 4, 5, 6]
l = 0 
r= len(valley_list)-1
mid = (l+r)//2
print(l , r, mid)
valley_list[mid]

0 6 3


3

In [45]:
def findPivot(arr):
    l = 0 
    r = len(arr) - 1
    pivot = -1
    while l<=r:
        mid = (l+r)//2
        print(l , r ,mid)
        print(arr[l], arr[r], arr[mid])
        print('---------')
        if arr[mid]<arr[mid+1] and arr[mid]<arr[mid-1]:
            pivot = mid
            break
        if mid>l and
            
        if arr[mid]<arr[l]:
            l = mid+1
        else:
            r = mid-1
    return pivot

valley_list = [12, 11, 8, 7, 6, 4, 3, 2, 1,13,14, 15, 16, 17]
findPivot(valley_list)

0 13 6
12 17 3
---------
7 13 10
2 17 14
---------
7 9 8
2 13 1
---------


8